### ISSUE TITLE
Flashtool Arduplane 2.76 - Baro Malfunction

### ISSUE THREAD

**Issue by SlipstreamFPV** [MegaPirateNG/ardupilot-mpng#102]
If you use the flashtool to upload Arduplane 2.76 on Crius AIOP V1.1 the baro malfunctions causing the altitude to jump all over the place (by hundreds of meters)

Flashing the latest 2.76 firmware with Arduino doesn't have the same problem.

**Comment by smurfy** [comment]
I will take a look. Can you tell me the file-name of the hex file from the flashtool? (firmwares subdirectory)
If you have more than one please delete all and restart the flashprocess / download with the settings you selected. after that only one hex file should exists.

**Comment by SlipstreamFPV** [comment]
Unfortunately I don't have time to reset the plane again, but looking at the date created on the firmware files it appears to be: 9087d1fca36f1219c4b3c818b0ef83de_e72bcb376b1d23dd8ac82214c3b055889376e067.hex

The other firmware files I had in the directory were:

91a87b7a90cc972b72ee6f3e799df9e6_e72bcb376b1d23dd8ac82214c3b055889376e067
762f06faaf39e31c2fe861b529447729_e72bcb376b1d23dd8ac82214c3b055889376e067
d15e7593c7f53cdc0100e4b515d0b5c0_e72bcb376b1d23dd8ac82214c3b055889376e067

Settings were RCTimer CRIUS V1
Regular PWM on A8-A15
JR (or Multiwii, can't quite remember this one)
APM:Plane
Auto Detect GPS
38400
Version 2.76

Anytime I tried to flash with the flashtool the Baro would go crazy. I test flew with Arduplane from your 3.1 branch yesterday (manually uploaded from arduino) and It all appeared fine. Is that beta for the plane or is that 2.76 stable? Where do I find the 2.76 stable if that's not it? Thanks!

**Comment by smurfy** [comment]
> Anytime I tried to flash with the flashtool the Baro would go crazy. I test flew with Arduplane from your 3.1 branch yesterday (manually uploaded from arduino) and It all appeared fine. Is that beta for the plane or is that 2.76 stable? Where do I find the 2.76 stable if that's not it? Thanks!

If you flash arduplane 2.76 via flashtool it should flash from this repo:
https://github.com/smurfy/ardupilot-mpng/tree/mpng_ArduPlane-2.76

The ArduPlane Code is 100% based on the offical stable version of ArduPlane 2.76 with mpng patches.

If you flash:
https://github.com/MegaPirateNG/ardupilot-mpng/tree/mpng-3.1-beta
This is based on ArduCopter 3.1 stable with some newer code for arduplane and the hardware adaption layer. the mpng portion of the code should be the same.

But i will analyse this later and come back to you.

**Comment by smurfy** [comment]
Ok, i did some more code comparisons. 

The mpng code of mpng_ArduPlane-2.76 and mpng-3.1-beta differs. Also the MPU6000 Code (Baro)

Reasons why the code differs:
- The mpng adaption is for ardupilot code around 1 1/2 months later so the code changed a bit
- Possible fixes on the way.

As i said before:

mpng_ArduPlane-2.76 uses the stable code of the offical ardupilot 2.76 + mpng patches from the master branch @399c745bbab957b5c61f1317b2f4d430e93ddbee . I also cherry picked all additions from the 3.0.1-r3 and 3.0.1-r4 branches. so its possible that @SirAlex fixed some problem with MPU6000_I2C code after that but the other nessesary changes on the code clutters it and i don't see it.

mpng-3.1-beta: is based on 3.1 stable + the mpng adaption which is newer than the one i use. Its also based on ArduCopter 3.1, it still contains the ArduPlane 2.76 Code but with some more changes in it which later (with much more changes and maybe fixes for that code) become ArduPlane 2.77.  

Thats the reason i started my ArduPlane fork in the first place, because the version which ships with arduCopter is not a stable version of ArduPlane because of the different release cycle. 

So hopefully @SirAlex can give us a hint whats different in the MPU6000 implementation which causes Baro Problems.

Also what exactly do you mean with it goes crazy. does the problem also occur on ground (in your room after flashing for example) or only if you actually in the air?

**Comment by SlipstreamFPV** [comment]
Thanks for the information. Do you think it's risky to run the arduplane that I am running from the 3.1 beta then? I don't mind some risk with my plane - just not excessive amounts :) I will see if I can switch to your branch with a working barometer using arduino. I will let you know the results.

The baro reads from 3000m or higher and drops to 0m within about 10 seconds, then back up to the top again and down and circles like that. This is on the ground after flashing with the firmware tool. I did not try flying the plane in this condition. Immediately reflashing using the 3.1beta code version of arduplane the baro is fine.

On another note the firmware tool looks like a fantastic program for all of those people without arduino experience or people after plug and play. Some excellent development going on with this project!

**Comment by smurfy** [comment]
> The baro reads from 3000m or higher and drops to 0m within about 10 seconds, then back up to the top again and down and circles like that. This is on the ground after flashing with the firmware tool. I did not try flying the plane in this condition. Immediately reflashing using the 3.1beta code version of arduplane the baro is fine.

yea i now notice it too, i'm currently trying to figure out whats wrong.

> On another note the firmware tool looks like a fantastic program for all of those people without arduino experience or people after plug and play. Some excellent development going on with this project!

thank you and yes that was my intention to help users easy access to mpng. but most thanks goes to siralex, without him mpng would not exist.

**Comment by SlipstreamFPV** [comment]
I just reflashed to your branch 2.76 using arduino and it's the same (baro malfunctions), so at least it looks like the firmware tool works perfectly :) Just a little bug in the arduplane code! Thanks for all your hard work. Which fork / version do you recommend running in the interim?

**Comment by smurfy** [comment]
I hopefully can fix it soon (as of today), in the meantime you still could use the 3.1beta.

Edit: also fu*k. MPU6000 is not the baro :) so i'm looking at the wrong place the whole time.

**Comment by smurfy** [comment]
Ok i found the change which broke the baro, (was the last one i merged lately) i reverted it and the baro should be ok. 

you can flash the new version using the flashtool. it automatically downloads the latest one.

**Comment by SlipstreamFPV** [comment]
Updated using the firmware tool. Looks good. Thanks for the quick fix and all the hard work you put into this project.

**Comment by smurfy** [comment]
@thisisglen if this issue is fixed, please close it. thank you.
