### ISSUE TITLE
3.1 release

### ISSUE THREAD

**Issue by quadmax66** [MegaPirateNG/ardupilot-mpng#115]
Hello Alex,

sorry, that I´m so impatient, but spring is comming and I´m longingly waiting for the 3.1 release. 
Can you tell me something about the state.
Do you have a roadmap for this version?
I`m sure that many people are interested in this topic.

Best regards and thanks a lot for your good work,
Max

**Comment by wengwah** [comment]
The 3.1 beta is already out. Sir Alex said that he needs more time for testing.

**Comment by quadmax66** [comment]
@wengwah: Where do you have this information from?

**Comment by smurfy** [comment]
https://github.com/MegaPirateNG/ardupilot-mpng/tree/mpng-3.1-beta

its a beta release, use with caution.

**Comment by quadmax66** [comment]
Sorry, my question was more related to the part that Alex needs more time for testing.
I don´t want to use 3.1 beta. I´m waiting for a 3.1 release.
I must know, if I can await 3.1 or if i must go back to 3.0.1 R4.

**Comment by smurfy** [comment]
Just look in previous issues @SirAlex commented.  As far as i know there are two main things with 3.1
- Some cpu performance issues, due to using i2c instead of spi and other stuff. (3.0.1 partly has the same issues)
- Hex file size. 3.1 added some new stuff and moved stuff around and we now run out of space on the flight controller. Looking for possible optimisations or disabling stuff (like logging)

If you want something quite stable for now you should stick with 3.0.1 R4 for now.

**Comment by SirAlex** [comment]
Hi!

Main problem is time! The 32bit controller consume lot of time (I'm fighting with debugging via ST-Link under Eclipse, but now it's ok). Will try to test 3.1 at this week.

**Comment by wengwah** [comment]
The r4 is just as good except that bugs in altitude hold when the filter is set to 42hz or higher. Do not set more than 20hz for filter else it may fly away.

**Comment by dinamitemic** [comment]
Some news about the release of the 3.1 not beta???

**Comment by smurfy** [comment]
3.1.5 R2 "Beta" is fairly stable. See #149
