### ISSUE TITLE
Problem setting dataflashlog 

### ISSUE THREAD

**Issue by auguste95** [MegaPirateNG/ardupilot-mpng#142]
Hi,

I have a problem with dataflash log recording : in the CLI, when I type logs, nothing happens, and I can't coose any parameter. Using LOG_BITMASK in standard parameters gives the same result : nothing to download. I didn't really make the quadcopter fly, but I just armed the board, which is a crius AIOP v1.1, and increased throttle without propellers, and made it move with my hands.

So I have 3 questions : 
Can the crius AIOP v1.1 record dataflash logs ?
Does the quad have to really fly to record some datas ?
Did I forget something ?

Thank you,

auguste95

**Comment by smurfy** [comment]
To my knowledge DataLogging is only available with crius v2.
also there is a real possibility due to flash size limitations that data logging will be disabled permanently. (even for crius v2)

I bought a sd card logger module a while back i would like to use for data logging but never had the time working on that :(

**Comment by auguste95** [comment]
Yes, after some researches, I came to the conclusion that you were right. Thank you for helping me :)
