### ISSUE TITLE
Stability patch?

### ISSUE THREAD

**Issue by FxFocus** [MegaPirateNG/ardupilot-mpng#49]
noob alert.
I came across this video, http://www.youtube.com/watch?v=42HnOx-4s-4, while googling for clues as to why my quads maiden flight went so badly wrong and it seems to fit my experience. So just wondering if this stability patch is implemented in megapirateng 3.0.1 R2? 

my quad is similar to the flite test wooden h quad but with crius aiop v2 fc. using plush 30 esc and dt750 motors, 11x4.7 props. Still waiting for gps and telemetry kit.

Thanks for reading,
Ed.

**Comment by smurfy** [comment]
based on the infos of the linked video the stability patch should be in 3.0.1

**Comment by FxFocus** [comment]
Thanks for reply. Should be yes. But to my untrained eye it looked like it may be implemented in R3 but maybe not in R2? Hence my request for confirmation.

**Comment by Homertje** [comment]
If I read correct MPNG 3.0.1R3 has some ArduCopter 3.1.0 patches (do not confuse that with ArduCopter 3.0.1 which is the basis of MPNG3.0.1) 

Personal Experience:
I have been running MPNG3.0.1 R2 and MPNG3.0.1R3b on a quad (DJI F450) with 750KV / 30A ESC / 10x5 prop, and on a Tri (Flitetest batbone) with 1275KV / 25A ESC / 9x4,7 prop,  both do not have this stability problem (running both R2 and R3) on full throttle both shoot up like a rocket without the "wobble", and gently drops down when throttling back.

Basics: 
IMHO one should always start off by checking PIDs and strengths anyway, so you can eliminate these kind of problems by setting up and tweaking PIDs, and if MPNG3.0.1R2 isn't treating you well, then switch over (temporarily) to either a older version or a newer version, I know i've used MPNG2.7 for a long time... before switching to MPNG3.0.1R2 and now lately MPNG3.0.1R3b.

Since it's all "hacked/ported" firmware based on arduino ported from ArduCopter, you can't eliminate problems completely anyway, so it's all tweaky tweaky! that, is for me just the fun of it... 

The task of the pilot is to deem a aircraft safe(or not) based of behavior during tests and test-flights.  With DIY drone building it's never JUST flashing the software onto your flightcontroller and fly..  If that is your goal, no offence, but then you might be better off getting a DJI Phantom with a NAZA (or similar, not endorsing DJI here) to just go out and fly.

**Comment by FxFocus** [comment]
Hi, thanks for your input. My intention was to simply hover a few feet off the ground in stabalize mode to see how the default settings worked and then tweak as needed. At first it did respond to throttle and hovered with a marked sideways wobble. I think it was when I touched the right stick that it took off and the throttle stopped responding. Reducing throttle had no effect until all the way back when the motors cut. So now I'm watching in horror as my quad turns upside down and begins to drop like a stone. I must say even in my panicked state I was impressed how the quad was able to recover when I reintroduced the throttle, instantly flipping upright soon as the motors came to life. Alas still no response from throttle when trying to bring it down and eventually crashed losing one boom and one prop. 

All repaired now and soon will try again. My impression is that rate (roll,pitch) most likely needs tweaking so have set it up on channel 6 so I can adjust in flight. Hoping an initially reduced P will stop the fly away problem at least..

All this is new to me so please forgive if my PID terminology is wrong.

**Comment by smurfy** [comment]
I think there is a bit of confusion with the versions here.

The stability patch was added in ArduCopter 3.0.0RC4.

MPNG is based on ArduCopter 3.0.1 stable.
The R2 or R3 is the version info for the MPNG release, not ArduCopter itself.

> If I read correct R3 has some ArduCopter 3.1.0 patches (do not confuse that with ArduCopter 3.0.1) 

And you are correct here. SirAlex used some of the timing and other stuff from 3.1.0

**Comment by Homertje** [comment]
Yup I fixed my reply to actually say MPNG for MegaPirate NG and AC/ArduCopter for the ArduPilot/ArduCopter software by 3DRobotics/APM:Copter

**Comment by smurfy** [comment]
@FxFocus i think you got your answer, please close this issue. thank you.

**Comment by FxFocus** [comment]
Sorry I had not realised I was opening a formal issue. Is there a place for general discussion of mpng? Thanks to all who responded. Still waiting for wind to drop before trying again.
