### ISSUE TITLE
Bluetooth does not work

### ISSUE THREAD

**Issue by cucpo** [MegaPirateNG/ardupilot-mpng#62]
Good day. I have probles with Functioning Bluetooth MegaPirateNG 3.0.1 R2. The board is Crius AIOP V2 by rctimer. On multiwii it works. Pls help me know the configuration of the BT module?

**Comment by smurfy** [comment]
On which serial port is your bluetooth connected? Make sure you connect your bluetooth either on Serial 0 or Serial 3.

**Comment by cucpo** [comment]
Hi. I use serial0 and dont work :-(

**Comment by smurfy** [comment]
what baudrate do you use? i think you are limited to 57k for bluetooth aswell.

**Comment by cucpo** [comment]
I use 112k in muttiwii it worked, but I'll try to 56k MPNG, and I know how it went

**Comment by cucpo** [comment]
Hello and 56k works but I never connected Crius V2 still disconnect and connect power to the bluetooth module. But through the terminal when you join so it only shows random group of characters must change something in configuration Arduino?

**Comment by smurfy** [comment]
don't know that language, but what google translate figured out, you said it works.
the offical arducopter and mpng for that matter uses 56k for all telemetry, bluetooth and 3dr. You should be able to communticate via missionplanner.

you also wrote something about terminal, not sure what you mean, but if you mean the Missionplanner console, this should only work over usb. but everything else in the missionplanner should work.
Edit: if you mean via serial console like putty or so that you see strange chars thats normal. you only see a console prompt over usb.

if this issue is therefore resolved, feel free to close it.

**Comment by aussiepage** [comment]
To get Bluetooth working you need to

1 set Bluetooth module to 57600 baud using at commands via serial port.
1. With copter off - press connect button on mission planner.  Obviously
   with correct serial port selected and 57600 baud.
2. Wait approximately 30 seconds for the connecting dialogue box to
   display.
3. Connect copter as soon as the dialogue appears - if you are too quick or
   too slow then connection will fail.

Works every time for me. One good thing is that you can connect to terminal
and download logs without using USB.

Hope this helps.

**Comment by cucpo** [comment]
Ok thx i probe this
