### ISSUE TITLE
Cannot arm quadcopter

### ISSUE THREAD

**Issue by RCJOSEB** [MegaPirateNG/ardupilot-mpng#8]
I updated my CRIUS V1.1 to 3.0.1.R2 following the instructions and also updated MP to V1.2.79.  I cannot arm the quadcopter nor do the scroll bars move in the rc calibration screen.

To test all out, I went back to V2.9.1 and am now able to arm the quadcopter again and perform an rc calibration via MP.

I am using a 9X with a FrSky module.

**Comment by SirAlex** [comment]
First of all, check you selected right RC input type and channel mapping.
Second, do eeprom erase. After flashing 3.0.1, go to terminal and run setup -> erase command.
Third, do all calibrations and try to arm. 3.0.1 and higher has PreArm checks, please read more about it here: http://copter.ardupilot.com/wiki/prearm_safety_check/

**Comment by RCJOSEB** [comment]
Is the rc input and channel mapping done in config-h or mplanner?  The hardware is connected correctly.   Why do i need to perform an eprom erase after flashing and not before?  Would that erase the firmware i just loaded if done afterwards?  Thanks for the help and all the coding work.  The website is really nice with lots of info.

**Comment by SirAlex** [comment]
1. There you can find how to configure RC: http://www.megapirateng.com/how-to-configure-mpng-3-0-1-firmware/
2. You must erase after, because if you do it in old version, it will store default parameters from 2.9. After flashing 3.x you will get default parameters from 2.9, not 3.x - so to work properly, you must do erase AFTER flashing firmware.

**Comment by RCJOSEB** [comment]
Got it, now I understand.  Thanks again Sir Alex!!!
